### ISSUE TITLE
Unable to load plugin due to compiler error

### ISSUE THREAD

**Issue by tim-ufer** [AndrejGobeX/TrackMania_AI#14]
I'm interested in using your project as a headstart for training my own AI with/in Trackmania. Unfortunately, I have trouble loading the plugin like some others before me. I'm running the starter edition of the game via the .exe (ubisoft connect install) on Windows and when trying to load your plugin in OpenPlanet per your instruction, I get a compiler error:
![image](https://user-images.githubusercontent.com/60989861/227666210-bf53a65a-5a17-453b-be12-29d3b8c3997a.png)
I initially also had the `invalid signature` error but resolved that by cloning the repo instead of downloading the zip.

**Comment by AndrejGobeX** [comment]
Yep, I have recently started to work on it again and encountered this as well. The issue is that the API changed (it is literally one line of code). I will try to update the plugin soon.

**Comment by AndrejGobeX** [comment]
I have updated the plugins and the readme. Now you just paste one file to "Plugins" folder (use the Ext version if you want to test with the TMEnv.py since it requires direction data). I have checked both plugins with a sccript (haven't tried the ML algos, but they should work).

Let me know if everything works and if you encounter any problems, feel free to reopen the issue.
